### ISSUE TITLE
OSError: libcudart.so.10.1: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by deep-recommend** [ai-forever/ghost#50]
![image](https://user-images.githubusercontent.com/81652465/194450617-e269723e-71ce-459b-af55-d2c1267ffa31.png)

OS compatibility issues when running google colab demo.

**Comment by cedro3** [comment]
The reason for the error is that the standard cuda version of google colab has changed.
3rd line of 'Install required libraries' !pip install mxnet-cu101mkl → !pip install mxnet-cu112
It is OK if you change to

**Comment by deep-recommend** [comment]
fixed! thanks!

**Comment by cedro3** [comment]
you're welcome.

iPhoneから送信
