### ISSUE TITLE
incorrect versions in requirements.txt

### ISSUE THREAD

**Issue by ihorrible** [ai-forever/ghost#52]
Hi FaceSwap,

Please state the correct versions in requirements.txt: 

- ERROR: Could not find a version that satisfies the requirement torch==1.6.0+cu101 (from versions: 1.7.1, 1.8.0, 1.8.1, 1.9.0, 1.9.1, 1.10.0, 1.10.1, 1.10.2, 1.11.0, 1.12.0, 1.12.1, 1.13.0)
ERROR: No matching distribution found for torch==1.6.0+cu101
- ERROR: Could not find a version that satisfies the requirement torchvision==0.7.0+cu101 (from versions: 0.1.6, 0.1.7, 0.1.8, 0.1.9, 0.2.0, 0.2.1, 0.2.2, 0.2.2.post2, 0.2.2.post3, 0.8.2, 0.9.0, 0.9.1, 0.10.0, 0.10.1, 0.11.0, 0.11.1, 0.11.2, 0.11.3, 0.12.0, 0.13.0, 0.13.1, 0.14.0)
ERROR: No matching distribution found for torchvision==0.7.0+cu101
- ERROR: Could not find a version that satisfies the requirement onnxruntime-gpu==1.4.0 (from versions: none)
ERROR: No matching distribution found for onnxruntime-gpu==1.4.0
- ERROR: Could not find a version that satisfies the requirement mxnet-cu101mkl (from versions: none)
ERROR: No matching distribution found for mxnet-cu101mkl
- ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
conda-repo-cli 1.0.4 requires pathlib, which is not installed.
anaconda-project 0.10.1 requires ruamel-yaml, which is not installed.

**Comment by Dutch77** [comment]
Look at this. I've done the heavy lifting for you. But you need to know some docker basics.
https://github.com/ai-forever/ghost/issues/51
