### ISSUE TITLE
OSError: libcudart.so.11.0

### ISSUE THREAD

**Issue by estebanpdl** [ai-forever/ghost#62]
I am trying to run `python inference.py` but I am getting this error:

`OSError: libcudart.so.11.0`

I tried to first install Cuda toolkit version 10, given that requirements.txt focuses on that version. However, I got some errors around dll libraries, so I ran: `pip install onnxruntime-gpu==1.8.0 mxnet-cu112==1.9.1`. This worked fine for those errors but now I am getting this one: `OSError: libcudart.so.11.0`.

I tried then to install some nvidia dependencies using this command: `sudo apt install nvidia-cuda-toolkit`. But the error persists.

I am using a WSL environment / Ubuntu on Windows.

Are there some methods to approach this error? Am I missing a specific version for pytorch? I have this Cuda version: `CUDA Version: 11.6`.

**Comment by tommy-qichang** [comment]
Same error. Any updates?

**Comment by ak3389** [comment]
Same problem, is there a solution?

**Comment by loboere** [comment]
any news? colab same issue
